# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenciaP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desocupado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=8)),
                ('fechaDeNacimiento', models.CharField(max_length=20)),
                ('experienciaLaboral', models.TextField(max_length=200)),
                ('formacion', models.TextField(max_length=200)),
                ('habilidades', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
