# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenciaP', '0005_auto_20170910_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='desocupado',
            name='trabajo',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
