# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenciaP', '0006_desocupado_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=8)),
                ('fechaDeNacimiento', models.CharField(max_length=20)),
                ('experienciaLaboral', models.TextField(max_length=200)),
                ('formacion', models.TextField(max_length=200)),
                ('habilidades', models.TextField(max_length=200)),
                ('trabajo', models.TextField(blank=True, max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
