# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenciaP', '0007_perfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desocupado',
        ),
    ]
