# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trabajo_trabajo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='trabajo_id',
        ),
    ]
