# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_trabajo_trabajo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='desocupado',
            name='booleane',
            field=models.BooleanField(default=False),
        ),
    ]
