# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_desocupado_booleane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desocupado',
            old_name='booleane',
            new_name='contratado',
        ),
    ]
